spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api-kotlin?createDatabaseIfNotExist=true
    username: root
    password: Dioge1997
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
