spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api-kotlin?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Dioge1997
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    url: jdbc:mysql://localhost:3306/api-kotlin
    user: root
    password: Dioge1997
    driver-class-name: com.mysql.cj.jdbc.Driver
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    database: mysql
